# Generated by Django 4.1.6 on 2023-06-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
                ('dateAdded', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('recipeName', models.ManyToManyField(to='cookbookPage.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='tagNames',
            field=models.ManyToManyField(to='cookbookPage.tag'),
        ),
    ]
