# Generated by Django 4.1.6 on 2023-02-10 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
                ('dateAdded', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('recipeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbookPage.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='tagName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbookPage.tag'),
        ),
    ]
