# Generated by Django 4.1.6 on 2023-06-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbookPage', '0002_rename_recipename_tag_recipenames'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='isBeingEditted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dateAdded',
            field=models.DateField(default=False),
        ),
    ]
