# Generated by Django 4.1.6 on 2023-02-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbookPage', '0002_alter_recipe_tagname_alter_tag_recipename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tagName',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='recipeName',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tagName',
            field=models.ManyToManyField(null=True, to='cookbookPage.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='recipeName',
            field=models.ManyToManyField(null=True, to='cookbookPage.recipe'),
        ),
    ]
