# Generated by Django 4.1.6 on 2023-02-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbookPage', '0003_remove_recipe_tagname_remove_tag_recipename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tagName',
            field=models.ManyToManyField(to='cookbookPage.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='recipeName',
            field=models.ManyToManyField(to='cookbookPage.recipe'),
        ),
    ]
