# Generated by Django 4.1.6 on 2023-06-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbookPage', '0003_recipe_isbeingeditted_alter_recipe_dateadded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='isBeingEditted',
            new_name='isBeingEdited',
        ),
    ]
